# Data preprocessing settings
preprocessing:
  tfidf_filtering:
    enabled: true
    threshold: 0.01
    remove_missing_words: true
  allowed_postags:
    - NOUN
    - ADJ
    - VERB
    - ADV
  stop_words_extra: ./stopwords
  spacy_model: en_core_web_sm
  spacy_disabled:
    - parser
    - ner
  debug:
    - enabled: false
  filter_extremes:
    no_below: 5 # filter out words that appear in less than 10 documents. Increasing this reduces the number of tokens in the dictionary.
    no_above: 0.5 # filter out words that appear in more than 50% of documents. Increasing this reduces the number of tokens in the dictionary.
    keep_n: 100000

# LDA model settings
lda:
  save_intermediate_models: true  # Save models to disk during optimization to reduce memory usage
  topic_range:
    start: 5 # start at 5 topics
    limit: 100 # limit at 50 topics
    step: 10
  gensim:
    ipo_params:
      random_state: 100
      update_every: 1
      chunksize: 128
      iterations: 1000
      passes: 10
      alpha: auto
      eta: auto
      per_word_topics: false
    analyst_params:
      random_state: 100
      update_every: 1
      chunksize: 1024
      iterations: 200
      passes: 50
      alpha: auto
      eta: auto
      per_word_topics: false

# Visualization settings
visualization:
  wordcloud:
    width: 800
    height: 400
    background_color: white


# Logging settings
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# Output settings
output:
  base_dir: outputs
  save_model: true
  save_metrics: true
  save_visualizations: true