# Data preprocessing settings
preprocessing:
  tfidf_filtering:
    enabled: true
    threshold: 0.01
    remove_missing_words: true
  model_type: lda
  vectorizer:
    - min_df: 3
    - max_features: 29999
    - token_pattern: '[a-zA-Z0-9]{4,}'
  allowed_postags:
    - NOUN
    - ADJ
    - VERB
    - ADV
  stop_words_extra: ./stopwords
  min_word_length: 3
  spacy_model: en_core_web_sm
  spacy_disabled:
    - parser
    - ner
  debug:
    - enabled: false

# LDA model settings
lda:
  optimize_topics: true
  topic_range:
    start: 1
    limit: 200
    step: 10
  gensim:
    random_state: 100
    update_every: 1
    chunksize: 1000
    iterations: 400
    passes: 20
    alpha: auto
    eta: auto
    per_word_topics: false
  sklearn:
    n_components: 20
    max_iter: 25
    learning_method: online
    learning_decay: 0.5
    batch_size: 100
    n_jobs: None
    random_state: 100

# Visualization settings
visualization:
  wordcloud:
    width: 800
    height: 400
    background_color: white


# Logging settings
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# Output settings
output:
  base_dir: outputs
  save_model: true
  save_metrics: true
  save_visualizations: true