# Data preprocessing settings
preprocessing:
  batch_size: 200
  num_docs: 0
  num_cores_preprocessing: 6
  test_perc: 0.1
  stop_words_extra: ./stopwords
  spacy_model: en_core_web_md
  spacy_disabled:
    - parser
    - ner
  allowed_postags:
    - NOUN
    - ADJ
    - VERB
    - ADV
  filter_extremes:
    no_below: 10 # filter out words that appear in less than 5 documents. Increasing this reduces the number of tokens in the dictionary.
    no_above: 0.5 # filter out words that appear in more than 50% of documents. Increasing this reduces the number of tokens in the dictionary.

# LDA model settings
lda:
  save_intermediate_models: true  # Save models to disk during optimization to reduce memory usage
  topic_range:
    start: 1 # start at 1 topics
    limit: 15 # limit at 50 topics
    step: 2
  gensim:
    random_seeds: [1, 3, 5]
    num_cores_lda: 1
    params:
      update_every: 1
      chunksize: 3000
      iterations: 3000
      passes: 10
      alpha: auto
      eta: auto
      per_word_topics: false
      
# Visualization settings
visualization:
  wordcloud:
    width: 800
    height: 400
    background_color: white


# Logging settings
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# Output settings
output:
  base_dir: outputs
  save_model: true
  save_metrics: true
  save_visualizations: true